// react-client/src/components/forms/Signin.jsx
import { useContext, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Input from "../ui/Input";
import Button from "../ui/Button";
import useAuthContext from "../../context/AuthContext";

const AuthContext = useAuthContext();

function FormSignin() {
  const { auth, setAuth } = useContext(AuthContext);

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState([]);

  const navigate = useNavigate();

  useEffect(() => {
    const signinCallback = () => {
      if (!auth) {
        return;
      }

      return navigate("/dashboard");
    };

    signinCallback();
  }, [auth]);

  const signin = async (e) => {
    e.preventDefault();

    // Prevent multiple accidental requests
    if (loading) {
      return;
    }

    // Update loading state
    setLoading(true);

    const { data, errors } = await fetch(
      "https://prod.tradify.dk/auth/provider/email/signin",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          password: password,
        }),
      }
    ).then((res) => res.json());

    // Update loading state
    setLoading(false);

    // Set localStorage
    localStorage.setItem("accessToken", data.accessToken);
    localStorage.setItem("refreshToken", data.refreshToken);

    // Set auth state in context
    return setAuth(data);
  };

  return (
    <>
      <form
        id="form-signin"
        className="w-full max-w-sm flex flex-col space-y-4"
        onSubmit={signin}
      >
        <Link to="/">
          <img
            crossOrigin="anonymous"
            className="w-2/3 mx-auto"
            src="https://prod.tradify.dk/content/public/tradify_logo.svg"
            alt="Tradify Logo"
          />
        </Link>
        <Input
          type="email"
          size="md"
          placeholder="Indtast email"
          label="E-mail"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
        <Input
          type="password"
          size="md"
          placeholder="Indtast password"
          label="Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
        <Link className="ml-auto text-sm text-indigo-500" to="/reset">
          Glemt password?
        </Link>
        {errors.length ? (
          <ul>
            {errors.map((error) => {
              return <li>* {error.msg}</li>;
            })}
          </ul>
        ) : null}
        <Button size="md" type="primary" loading={loading}>
          Log på
        </Button>{" "}
        <div className="text-xs text-zinc-400 flex justify-end">
          <span>
            Har du ikke en konto?{" "}
            <Link className="text-indigo-500" to="/signup">
              Opret konto
            </Link>
          </span>
        </div>
      </form>
    </>
  );
}

export default FormSignin;

// nuxt-client/components/Form/Signin.vue
<script setup>
import useAuthStore from "../../stores/AuthStore";
import { storeToRefs } from "pinia";

const authStore = useAuthStore();
const authStoreRefs = storeToRefs(authStore);
const router = useRouter();

// Loading state
const loading = ref(false);

// Store credentials
const body = ref({
  email: null,
  password: null,
});

// Main signin method
const signin = async () => {
  if (loading.value || !(body.value.email && body.value.password)) {
    return;
  }

  // Update loading state
  loading.value = true;

  // Request signin
  const { data, errors } = await fetch(
    "https://prod.tradify.dk/auth/provider/email/signin",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body.value),
    }
  ).then((res) => res.json());

  // Update loading state
  loading.value = false;

  if (errors.length) {
    // TODO: Error handling
    return;
  }

  // Set accessToken cookie
  const accessToken = useCookie("accessToken");
  accessToken.value = data.accessToken;
  authStoreRefs.accessToken.value = data.accessToken;

  // Set refreshToken cookie
  const refreshToken = useCookie("refreshToken");
  refreshToken.value = data.refreshToken;
  authStoreRefs.refreshToken.value = data.refreshToken;

  // Set user object in store
  authStoreRefs.user.value = data.user;

  // Redirect to dashboard
  return router.push("/dashboard");
};
</script>

<template>
  <form id="form-signin" @submit.prevent="signin">
    <NuxtLink class="flex justify-center items-center" to="/">
      <Logo />
    </NuxtLink>
    <div class="border-2 border-zinc-800 p-8 rounded flex flex-col space-y-4">
      <h2 class="text-2xl">Log på</h2>
      <Input
        type="email"
        placeholder="Indtast e-mail"
        label="E-mail"
        @input="(e) => (body.email = e.value)"
      />
      <Input
        type="password"
        placeholder="Indtast password"
        label="Password"
        @input="(e) => (body.password = e.value)"
      />
      <div class="flex justify-end">
        <NuxtLink class="text-sm text-indigo-500 hover:text-indigo-600" to="/"
          >Glemt password?</NuxtLink
        >
      </div>
      <Button :loading="loading">Log på</Button>
      <div class="flex justify-between items-center space-x-4">
        <span class="border border-zinc-800 w-full"></span>
        <span class="text-sm text-zinc-400">Eller</span>
        <span class="border border-zinc-800 w-full"></span>
      </div>
      <Button @click.prevent="router.push('/signup')" type="secondary"
        >Opret konto</Button
      >
    </div>
  </form>
</template>

<style>
#form-signin {
  @apply w-full max-w-md flex flex-col space-y-4;
}
</style>
