// src/components/ui/Sidenav.jsx
import { Link } from "react-router-dom";
import {
  HomeIcon,
  ArrowsRightLeftIcon,
  UserIcon,
  Cog6ToothIcon,
} from "@heroicons/react/24/outline";

function Sidenav() {
  return (
    <>
      <aside className="fixed w-64 top-0 bottom-0 left-0 p-4 border-r border-zinc-800">
        <div className="w-full h-full relative flex flex-col space-y-16">
          <Link to="/dashboard">
            <img
              className="w-3/4"
              crossOrigin="anonymous"
              src="https://prod.tradify.dk/content/public/tradify_logo.svg"
              alt="Tradify Logo"
            />
          </Link>
          <ul className="flex flex-col space-y-2">
            <li>
              <Link
                className="p-4 bg-zinc-800 flex items-center space-x-4 rounded"
                to="/"
              >
                <HomeIcon className="w-6 h-6" />
                <span className="font-semibold text-sm">Hjem</span>
              </Link>
            </li>
            <li>
              <Link
                className="p-4 flex items-center space-x-4 text-zinc-400 rounded hover:bg-zinc-800 hover:text-zinc-50"
                to="/"
              >
                <ArrowsRightLeftIcon className="w-6 h-6" />
                <span className="font-semibold text-sm">Mine handler</span>
              </Link>
            </li>
            <li>
              <Link
                className="p-4 flex items-center space-x-4 text-zinc-400 rounded hover:bg-zinc-800 hover:text-zinc-50"
                to="/"
              >
                <UserIcon className="w-6 h-6" />
                <span className="font-semibold text-sm">Min profil</span>
              </Link>
            </li>
            <li>
              <Link
                className="p-4 flex items-center space-x-4 text-zinc-400 rounded hover:bg-zinc-800 hover:text-zinc-50"
                to="/"
              >
                <Cog6ToothIcon className="w-6 h-6" />
                <span className="font-semibold text-sm">Indstillinger</span>
              </Link>
            </li>
          </ul>
        </div>
      </aside>
    </>
  );
}

export default Sidenav;

// nuxt-client/components/Sidenav.vue
<script setup>
import {
  HomeIcon,
  ArrowsRightLeftIcon,
  UserIcon,
  Cog8ToothIcon,
} from "@heroicons/vue/24/outline";
</script>

<template>
  <nav id="sidenav">
    <NuxtLink id="logo-link" to="/dashboard">
      <Logo size="xs" />
    </NuxtLink>
    <ul class="flex flex-col space-y-4">
      <li>
        <NuxtLink class="router-link" to="/dashboard">
          <HomeIcon class="h-6 w-6" />
          <span>Hjem</span>
        </NuxtLink>
      </li>
      <li>
        <NuxtLink class="router-link" to="/trades">
          <ArrowsRightLeftIcon class="w-6 h-6" />
          <span>Mine handler</span>
        </NuxtLink>
      </li>
      <li>
        <NuxtLink class="router-link" to="/profile">
          <UserIcon class="h-6 w-6" />
          <span>Min profil</span>
        </NuxtLink>
      </li>
      <li>
        <NuxtLink class="router-link" to="/settings">
          <Cog8ToothIcon class="h-6 w-6" />
          <span>Indstillinger</span>
        </NuxtLink>
      </li>
    </ul>
  </nav>
</template>

<style>
#sidenav {
  @apply fixed top-0 bottom-0 left-0 w-64 p-4 border-r-2 border-zinc-800 flex flex-col space-y-8;
}

#sidenav .router-link {
  @apply flex items-center space-x-4 p-4 rounded font-semibold text-sm text-zinc-400 hover:text-zinc-100;
}

#sidenav {
  @apply bg-transparent;
}

#sidenav .router-link-active,
#sidenav .router-link-exact-active {
  @apply text-zinc-100 bg-zinc-800;
}

#sidenav #logo-link {
  @apply bg-transparent;
}
</style>
