// nuxt-client/pages/signin.vue
<script setup>
import useAuthStore from "../stores/AuthStore";
import { storeToRefs } from "pinia";

definePageMeta({
    layout: "auth"
})

const authStore = useAuthStore();
const authStoreRefs = storeToRefs(authStore);
const router = useRouter();


// Loading state
const loading = ref(false);

// Store credentials
const body = ref({
    email: null,
    password: null
})

// Main signin method
const signin = async () => {
    if (loading.value || !(body.value.email && body.value.password)) {
        return;
    }

    // Update loading state
    loading.value = true;

    // Request signin
    const { data, errors } = await fetch("https://prod.tradify.dk/auth/provider/email/signin", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(body.value)
    })
        .then(res => res.json())

    // Update loading state
    loading.value = false;

    if (errors.length) {
        // TODO: Error handling
        return
    }

    // Set accessToken cookie
    const accessToken = useCookie("accessToken");
    accessToken.value = data.accessToken;

    // Set refreshToken cookie
    const refreshToken = useCookie("refreshToken");
    refreshToken.value = data.refreshToken;

    // Set user object in store
    authStoreRefs.user.value = data.user;

    // Redirect to dashboard
    return router.push("/dashboard");
}
</script>

<template>
    <section id="page-signin">
        <form id="form-signin" @submit.prevent="signin">
            <NuxtLink class="flex justify-center items-center" to="/">
                <Logo />
            </NuxtLink>
            <div class="border-2 border-zinc-800 p-8 rounded flex flex-col space-y-4">
                <h2 class="text-2xl">Log på</h2>
                <Input type="email" placeholder="Indtast e-mail" label="E-mail" @input="e => body.email = e.value" />
                <Input type="password" placeholder="Indtast password" label="Password"
                    @input="e => body.password = e.value" />
                <div class="flex justify-end">
                    <NuxtLink class="text-sm text-indigo-500 hover:text-indigo-600" to="/">Glemt password?</NuxtLink>
                </div>
                <Button :loading="loading">Log på</Button>
                <div class="flex justify-between items-center space-x-4">
                    <span class="border border-zinc-800 w-full"></span>
                    <span class="text-sm text-zinc-400">Eller</span>
                    <span class="border border-zinc-800 w-full"></span>
                </div>
                <Button @click.prevent="router.push('/signup')" type="secondary">Opret konto</Button>
            </div>
        </form>
    </section>
</template>

<style>
#page-signin {
    @apply grid place-items-center min-h-screen;
}

#form-signin {
    @apply w-full max-w-md flex flex-col space-y-4;
}
</style>

// src/pages/Signin.jsx
import { useContext, useEffect, useState } from "react";
import useAuthContext from "../context/AuthContext";
import { Link, useNavigate } from "react-router-dom";

const AuthContext = useAuthContext();

function Signin() {
  const { auth, setAuth } = useContext(AuthContext);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errors, setErrors] = useState([]);

  const navigate = useNavigate();

  useEffect(() => {
    const checkAuth = () => {
      if (auth) {
        return navigate("/dashboard");
      }
    };
    checkAuth();
  }, [auth, navigate]);

  const signin = async (e) => {
    e.preventDefault();

    const { data, errors } = await fetch(
      "https://prod.tradify.dk/auth/provider/email/signin",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: email,
          password: password,
        }),
      }
    ).then((res) => res.json());

    if (errors.length) {
      return setErrors(errors);
    }

    localStorage.setItem("accessToken", data.accessToken);
    localStorage.setItem("refreshToken", data.refreshToken);

    return setAuth(data);
  };

  return (
    <>
      <section className="h-screen grid place-items-center">
        <div className="flex flex-col space-y-4 w-full max-w-sm">
          <h1 className="text-4xl text-center">Log på</h1>
          <form
            className="p-4 bg-slate-50 rounded shadow-sm flex flex-col space-y-4"
            onSubmit={signin}
          >
            <div className="flex flex-col space-y-2">
              <label
                className="uppercase text-sm text-slate-400"
                htmlFor="email"
              >
                E-mail
              </label>
              <input
                className="shadow-sm border border-slate-100 py-2 px-6 rounded"
                type="email"
                placeholder="Indtast e-mail"
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="flex flex-col space-y-2">
              <label
                className="uppercase text-sm text-slate-400"
                htmlFor="email"
              >
                Password
              </label>
              <input
                className="shadow-sm border border-slate-100 py-2 px-6 rounded"
                type="password"
                placeholder="Indtast password"
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <Link className="text-sm text-indigo-500 text-right" to="/">
              Glemt password?
            </Link>
            {errors.length ? (
              <ul className="flex flex-col space-y-2">
                {errors.map((error, index) => {
                  return (
                    <li className="text-red-500 text-xs" key={index}>
                      {JSON.stringify(error)}
                    </li>
                  );
                })}
              </ul>
            ) : null}
            <button className="py-2 px-6 rounded bg-indigo-500 shadow-sm font-semibold text-zinc-50">
              Log på
            </button>
          </form>
          {JSON.stringify(auth)}
        </div>
      </section>
    </>
  );
}

export default Signin;
